"""
Freezes the command surface the fman plugin loader discovers.

The loader (fman/impl/plugins/plugin.py:_iterate_classes) only sees classes
reachable as attributes of the top-level `core` package - it walks dir(core),
not the filesystem. So a module split that forgets a `from .x import *` line
silently drops those commands: no import error, no other test failure, they
just stop existing in the app. This test names the missing one.

EXPECTED is regenerated by calling _registered() below, never by a second
copy of the predicate:

	cd src/main/resources/base/Plugins/Core
	PYTHONPATH=../../../../python python -c \
		"from core.tests.test_command_registry import _registered; \
		 print(sorted(_registered()))"
"""
from fman import ApplicationCommand, DirectoryPaneCommand, DirectoryPaneListener
from unittest import TestCase

import core
import inspect

EXPECTED = frozenset({
	'About', 'ArchiveOpenListener', 'CenterWindow', 'CommandPalette',
	'CompareDirectories', 'Copy', 'CopyPathsToClipboard', 'CopyToClipboard',
	'CreateAndEditFile', 'CreateDirectory', 'Cut', 'DecreasePaneFontSize',
	'DeletePermanently', 'Deselect', 'DoNothing', 'DragAndDropListener',
	'GoBack', 'GoForward', 'GoHome', 'GoTo', 'GoToAppData', 'GoToDesktop',
	'GoToDocuments', 'GoToDownloads', 'GoToListener', 'GoToLocalAppData',
	'GoToProgramData', 'GoToProgramFiles', 'GoToProgramFilesX86',
	'GoToRootOfCurrentDrive', 'GoToTemp', 'GoUp', 'Help', 'HistoryListener',
	'IncreasePaneFontSize', 'InitColumnVisibility', 'InitHiddenFilesFilter',
	'InitPaneFontSize', 'InstallPlugin', 'InvertSelection', 'ListPlugins',
	'LocationBarListener', 'Minimize', 'Move', 'MoveCursorDown',
	'MoveCursorEnd', 'MoveCursorHome', 'MoveCursorPageDown',
	'MoveCursorPageUp', 'MoveCursorUp', 'MoveToTrash', 'Open',
	'OpenDataDirectory', 'OpenDirectory', 'OpenFile', 'OpenInLeftPane',
	'OpenInRightPane', 'OpenListener', 'OpenNativeFileManager', 'OpenOrView',
	'OpenSelectedFiles', 'OpenTerminal', 'OpenWith', 'OpenWithEditor', 'Pack',
	'Paste', 'PasteCut', 'Quit', 'Reload', 'ReloadPlugins',
	'RememberSortSettings', 'RemovePlugin', 'Rename', 'RenameListener',
	'ResetFont', 'ResetPaneFontSize', 'SelectAll', 'SelectFont',
	'SelectIconSet', 'SelectTheme', 'SetIconColor', 'SetIconSize',
	'SetWindowOpacity', 'ShowAllPanes', 'ShowExplorerProperties',
	'ShowOnlyActivePane', 'ShowReleaseNotes', 'ShowVolumes', 'SortByColumn',
	'SwitchPanes', 'Symlink', 'ToggleExecutableIcons', 'ToggleHiddenFiles',
	'ToggleModifiedColumn', 'ToggleNetworkIcons', 'ToggleSelection',
	'ToggleSizeColumn', 'UpdateWindowTitle', 'ViewFile',
	'ViewFileInOtherPane', 'ZenOfFman', 'none'
})

def _registered():
	kinds = (ApplicationCommand, DirectoryPaneCommand, DirectoryPaneListener)
	result = set()
	for name in dir(core):
		value = getattr(core, name)
		# [1:] skips the class itself, so the three base classes - which are
		# also attributes of `core` via its star imports - are not counted.
		if inspect.isclass(value) \
				and any(k in inspect.getmro(value)[1:] for k in kinds):
			result.add(name)
	# frozenset, not set: assertEqual only dispatches to the set-difference
	# message when both sides have the same type. A plain set here degrades
	# the failure into a truncated repr that does not name the lost command.
	return frozenset(result)

class CommandRegistryTest(TestCase):
	def test_every_command_is_still_reachable_from_core(self):
		self.assertEqual(EXPECTED, _registered())
